fix: DatePicker getting closed when Calendar dropdown is open and clicked outside of the dropdown
raystack/apsara pull request #134
Opened 2024-08-07 08:51 UTC by singh-pk

2024-08-07 08:56 UTC, Neghat-Nazir approved these changes

2024-08-08 06:40 UTC, rsbh requested changes

2024-08-08 06:40 UTC, rsbh commented on packages/raystack/calendar/calendar.tsx
> +function DropDown({ options = [], value, onChange, onDropdownOpen }: (DropdownProps & onDropdownOpen)) {
add a default value for `onDropdownOpen`, otherwise it will crash

2024-08-08 07:01 UTC, rsbh approved these changes

2024-08-08 07:01 UTC, merged